# .air.toml
# we have created this file so as config the air package and only reload after we chnage the .go extension files only and not every html or css file.
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ./main.go"
bin = "./tmp/main.exe"
include_ext = ["go"]  # Only watch .go files
exclude_dir = ["tmp", "vendor", "node_modules", "public"]
delay = 1000  # ms

[log]
time = true

[misc]
clean_on_exit = true